### PR TITLE
Add Navdy 1.0.146

### PR DESCRIPTION
**Pull request by schneidmaster**
Desktop application used to update offline maps on a [Navdy](https://www.navdy.com/) (heads-up display for a car). I poked around a little looking for a versioned download URL but couldn't find one.

---

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-drivers/pulls
[closed issues]: https://github.com/caskroom/homebrew-drivers/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
What I did to find the versioned URL:

1. Opened website in Chrome.
2. Clicked download link.
3. Pressed <kbd>⇧</kbd><kbd>⌘</kbd><kbd>J</kbd> (Downloads tab).
4. Final URL was there.

Or via CLI: `curl --location --silent --head 'https://downloads.navdy.com/desktop_support/release/navdy_desktop_mac.dmg' | grep '^Location'`.

**Comment by schneidmaster** [comment]
Ah. Good find, thanks.

**Comment by schneidmaster** [comment]
@vitorgalvao Out of curiosity/for the future, are there guidelines for what to put in `delete` vs. `trash` for the `zap`? My original config was based on the changes a maintainer made to my PR #93 but in this case it seems some of it was backwards.

**Comment by vitorgalvao** [comment]
@schneidmaster Yep, that one had some parts backward. Fixing in https://github.com/caskroom/homebrew-drivers/pull/148.

Things that contain preferences/data the user may want to recover are `trash`. The rest is `delete`.

**Comment by schneidmaster** [comment]
Makes sense. Thanks!

**Pull request merged**
