### PR TITLE
Migrate 6 Casks from caskroom/versions

### PR DESCRIPTION
**Pull request by miccal**
See https://github.com/caskroom/homebrew-versions/issues/3232 for reference.

### CODE REVIEW

**Comment by miccal** [comment]
```
Error: audit failed for 2 casks: scansnap-manager-sv600 unifi-controller-beta
```

I cannot seem to find updated `url`'s for these two - I cannot find a `pkg` installer for `scansnap-manager-sv600`, only a manual `app`.

There does not seem to be a beta version of `unifi-controller` at the moment.

I would just remove these two - @vitorgalvao thoughts?

PS: Is there an easy way to remove a file from a PR?

**Comment by vitorgalvao** [comment]
> I would just remove these two

Agreed. Always up for removal.

> would you mind if we merge this and caskroom/homebrew-versions#3236, then I will open new PR's to remove these two

Sure. Go right ahead.

**Comment by miccal** [comment]
Actually, it seems I do not have the ability to merge in this repo yet.

**Comment by vitorgalvao** [comment]
> Actually, it seems I do not have the ability to merge in this repo yet.

No one did. Forgot about that. Should be fixed now.

**Pull request merged**
