### PR TITLE
Update ubiquiti-unifi-controller to 5.7.20

### PR DESCRIPTION
**Pull request by MindTooth**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

LTS is still at candidate stage.

### CODE REVIEW

**Comment by MindTooth** [comment]
My bad, I saw that you pushed as a force pushed my commit.  Please go ahead ;)

**Comment by commitay** [comment]
Sorry and thanks!

**Comment by MindTooth** [comment]
At least I was on the right track ;)  Maybe a style test for removing unnecessary spaces.  Did not report via `brew cask style`.

**Comment by commitay** [comment]
> Maybe a style test for removing unnecessary spaces.

I _think_ that `style` does do this but it doesn't seem to be working at the moment.

**Pull request merged**
