### PR TITLE
Rename cuda to nvidia-cuda

### PR DESCRIPTION
**Pull request by commitay**

### CODE REVIEW

**Comment by commitay** [comment]
Passes `audit`

**Comment by miccal** [comment]
Verified locally.

**Comment by star114** [comment]
Hi,

I'm just wondering why you change the cask name.
Were there any problems with the name?

Regards,
Heesik

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/issues/39867

**Comment by star114** [comment]
Thanks for your reply!

**Pull request merged**
